# Generated by Django 4.0.1 on 2022-04-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanıcı_adı', models.CharField(max_length=150)),
                ('dosya', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
