# Generated by Django 4.0.1 on 2022-04-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
    ]
