# Generated by Django 4.0.1 on 2022-04-10 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_about_user_abouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='abouts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='posts.about'),
        ),
    ]
