# Generated by Django 4.0.1 on 2022-04-10 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_user_abouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='abouts',
        ),
    ]
