# Generated by Django 4.0.1 on 2022-04-10 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_user_abouts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
    ]
