# Generated by Django 4.0.1 on 2022-04-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='about1',
        ),
    ]
